---
title: "Prep Test Dataset"
author: "Heidi Rodenhizer"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(sf)
library(dplyr)
library(stringr)
library(lubridate)
library(reticulate)
```

```{r}
years <-  c('2022', '2022', '2023', '2023', '2022', '2023',
            '2022', '2023', '2022', '2023', '2023', '2022')
```

```{r}
polys <- read_sf('./input_data/rts_dataset_test_polygons.shp')

polys <- polys |>
  bind_cols(
    st_coordinates(
      st_centroid(
        polys
      ) |>
          st_transform('EPSG:4326')
    )
  ) |>
  rename(CentroidLat = Y, CentroidLon = X) |>
  mutate(RegionName = 'Yamal-Gydan',
         CreatorLab = 'Rodenhizer',
         BaseMapDate = paste0(years, '-05-01,', years, '-09-30'),
         BaseMapSource = 'WorldView-2',
         BaseMapResolution = 4,
         TrainClass = 'Positive',
         LabelType = 'Polygon') |>
  select(id, 
         CentroidLat, 
         CentroidLon, 
         RegionName, 
         CreatorLab,
         ContributionDate = ContrDate, 
         BaseMapDate, 
         BaseMapSource, 
         BaseMapResolution,
         TrainClass,
         LabelType)
```

```{r}
current_data <- polys |>
  filter(ContributionDate == as_date('2023-09-01'))

new_data <- polys |>
  filter(ContributionDate == as_date('2023-09-28'))
```

```{r}
current_data <- current_data |>
  mutate(seed = str_flatten(c(CentroidLat,
                              CentroidLon,
                              RegionName,
                              CreatorLab,
                              ContributionDate,
                              BaseMapDate,
                              BaseMapSource,
                              BaseMapResolution,
                              TrainClass,
                              LabelType)),
         .by = c(CentroidLat, CentroidLon))

rts_seeds <- pull(current_data, seed)
```

```{python}
import uuid
```

```{python}
rts_uids = [str(uuid.uuid5(uuid.NAMESPACE_DNS, name = seed)) for seed in r.rts_seeds]
r.rts_uids = rts_uids
```

```{r}
current_data <- current_data |>
  mutate(UID = rts_uids,
         StabilizedRTS = '',
         MergedRTS = '',
         Area = as.numeric(st_area(geometry))) |>
  select(CentroidLat, 
         CentroidLon, 
         RegionName, 
         CreatorLab,
         ContributionDate, 
         BaseMapDate, 
         BaseMapSource, 
         BaseMapResolution,
         TrainClass,
         LabelType,
         UID,
         StabilizedRTS,
         MergedRTS,
         Area)

new_data <- new_data |>
  bind_rows(new_data |>
              filter(id == 4) |>
              mutate(id = 13,
                     BaseMapDate = '2022-05-01,2022-9-30')) |>
  mutate(CustomColumn1 = NA) |>
  select(-geometry)
```

```{r}
st_write(current_data,
         'input_data/rts_dataset_test_polygons_current.shp',
         append = FALSE)
st_write(current_data,
         'input_data/rts_dataset_test_polygons_current.geojson',
         append = FALSE)

st_write(new_data,
         'input_data/rts_dataset_test_polygons_new.shp',
         append = FALSE)
st_write(new_data,
         'input_data/rts_dataset_test_polygons_new.geojson',
         append = FALSE)
```

